# Generated by Django 5.2.10 on 2026-01-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, db_index=True, max_length=2048)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('has_precise_location', models.BooleanField(default=False)),
                ('neighborhood_data', models.JSONField(blank=True, default=dict)),
                ('neighborhood_score', models.FloatField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('source_provider', models.CharField(blank=True, max_length=50)),
                ('analysis_radius', models.IntegerField(default=500)),
                ('parsing_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analiza Lokalizacji',
                'verbose_name_plural': 'Analizy Lokalizacji',
                'ordering': ['-created_at'],
            },
        ),
    ]
