# Generated by Django 5.2.10 on 2026-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_analysis', '0002_add_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationanalysis',
            name='persona_adjusted_score',
            field=models.FloatField(blank=True, help_text='Score dostosowany do profilu użytkownika', null=True),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='scoring_data',
            field=models.JSONField(blank=True, default=dict, help_text='Wynik scoringu z dynamicznymi wagami'),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='user_profile',
            field=models.CharField(choices=[('family', 'Rodzina'), ('urban', 'Singiel / City Life'), ('investor', 'Inwestor')], default='family', help_text='Profil użytkownika użyty do analizy', max_length=20),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='verdict_data',
            field=models.JSONField(blank=True, default=dict, help_text='Werdykt decyzyjny (polecane/warunkowo/niepolecane)'),
        ),
    ]
