/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CustomDataTable: typeof import('./components/DataTable/CustomDataTable.vue')['default']
    FlatCreateForm: typeof import('./components/Flats/FlatCreateForm.vue')['default']
    FlatDetailCard: typeof import('./components/Flats/FlatDetailCard.vue')['default']
    FlatsGallery: typeof import('./components/Flats/FlatsGallery.vue')['default']
    FloatingConfigurator: typeof import('./components/FloatingConfigurator.vue')['default']
    FooterDynamicDialog: typeof import('./components/DataTable/FooterDynamicDialog.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayoutImportForm: typeof import('./components/Layouts/LayoutImportForm.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
